/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fodboldturnering;

/**
 *
 * @author Andreas
 */
public class TurneringsGUI extends javax.swing.JFrame {

    /**
     * Creates new form TurneringsGUI
     */
    public TurneringsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jSpillerKampeSe1 = new javax.swing.JTextField();
        jSpillerMålSe1 = new javax.swing.JTextField();
        jSpillerSelvmålSe1 = new javax.swing.JTextField();
        jSpillerAdvarselSe1 = new javax.swing.JTextField();
        jSpillerUdvisningSe1 = new javax.swing.JTextField();
        jSpillerHøjesteMålSe1 = new javax.swing.JTextField();
        jSpillerBedømmelser1 = new javax.swing.JComboBox();
        jSpillerSamletBedømmelseSe1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jOpretKamp = new javax.swing.JButton();
        jKamprapporter = new javax.swing.JComboBox();
        jTurneringsstilling = new javax.swing.JComboBox();
        jSøgefelt = new javax.swing.JTextField();
        jSøgeknap = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jHjemmeOpret = new javax.swing.JTextField();
        jUdeOpret = new javax.swing.JTextField();
        jStedOpret = new javax.swing.JTextField();
        jDatoOpret = new javax.swing.JTextField();
        jTidOpret = new javax.swing.JTextField();
        jOpretStartRapport = new javax.swing.JButton();
        jAnnullerStartRapport = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTeRundenrOpret = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDommerOpret = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jStedSe = new javax.swing.JTextField();
        jDatoSe = new javax.swing.JTextField();
        jTidSe = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jHjemmeholdSe = new javax.swing.JTextField();
        jKampRedigerSe = new javax.swing.JButton();
        jKampTilbageSe = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jStartopstillingSe = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jDommerSe = new javax.swing.JTextField();
        jRundenrSe = new javax.swing.JTextField();
        jMålHjemmeSe = new javax.swing.JComboBox();
        jSelvmålHjemmeSe = new javax.swing.JComboBox();
        jAdvarselHjemmeSe = new javax.swing.JComboBox();
        jUdvisningHjemmeSe = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jMålUdeSe = new javax.swing.JComboBox();
        jSelvmålUdeSe = new javax.swing.JComboBox();
        jAdvarselUdeSe = new javax.swing.JComboBox();
        jUdvisningUdeSe = new javax.swing.JComboBox();
        jBegivenhedSe = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jGemBegivenhed = new javax.swing.JButton();
        jAnnullerBegivenhed = new javax.swing.JButton();
        jBegivenhedHoldRediger = new javax.swing.JComboBox();
        jBegivenhedSpillerRediger = new javax.swing.JComboBox();
        jBegivenhedTidRediger = new javax.swing.JTextField();
        jBegivenhedRediger = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHoldListe = new javax.swing.JList();
        jStillingTilbage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPlaceringsListe = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jResultatListe = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jMålListe = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPointListe = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jHoldPlaceringSe = new javax.swing.JTextField();
        jHoldTrænerSe = new javax.swing.JTextField();
        jHoldKampeSe = new javax.swing.JTextField();
        jHoldAdresseSe = new javax.swing.JTextField();
        jHoldNavnSe = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jHoldRediger = new javax.swing.JButton();
        jHoldTilbage = new javax.swing.JButton();
        jHoldSpillerSe = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jHoldSejreSe = new javax.swing.JTextField();
        jHoldUafgjortSe = new javax.swing.JTextField();
        jHoldTabteSe = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jHoldPointSe = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jHoldMålSe = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jHoldPlaceringRediger = new javax.swing.JTextField();
        jHoldKampeRediger = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jHoldSejreRediger = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jHoldUafgjortRediger = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jHoldTabteRediger = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jHoldMålRediger = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jHoldPointRediger = new javax.swing.JTextField();
        jHoldAnnuller = new javax.swing.JButton();
        jHoldGem = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSpillerAdvarselSe = new javax.swing.JTextField();
        jSpillerSelvmålSe = new javax.swing.JTextField();
        jSpillerMålSe = new javax.swing.JTextField();
        jSpillerKampeSe = new javax.swing.JTextField();
        jSpillerAlderSe = new javax.swing.JTextField();
        jSpillerNavnSe = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSpillerRediger = new javax.swing.JButton();
        jSpillerTilbage = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jSpillerUdvisningSe = new javax.swing.JTextField();
        jSpillerBedømmelserSe = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jSpillerSamletBedømmelseSe = new javax.swing.JTextField();
        jSpillerHøjesteMålSe = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jSpillerGem = new javax.swing.JButton();
        jSpillerAnnuller = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jSpillerKampeRediger = new javax.swing.JTextField();
        jSpillerMålRediger = new javax.swing.JTextField();
        jSpillerSelvmålRediger = new javax.swing.JTextField();
        jSpillerAdvarselRediger = new javax.swing.JTextField();
        jSpillerUdvisningRediger = new javax.swing.JTextField();
        jSpillerHøjesteMålRediger = new javax.swing.JTextField();
        jSpillerBedømmelserRediger = new javax.swing.JComboBox();
        jSpillerSamletBedømmelseRediger = new javax.swing.JTextField();

        jLabel45.setText("Kampe");

        jLabel46.setText("Mål");

        jLabel63.setText("Selvmål");

        jLabel64.setText("Advarsler");

        jLabel65.setText("Udvisninger");

        jLabel66.setText("Højeste antal mål i en kamp");

        jLabel67.setText("Bedømmelser");

        jLabel68.setText("Samlet bedømmelse");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jOpretKamp.setText("Opret kamp");
        jOpretKamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpretKampActionPerformed(evt);
            }
        });

        jKamprapporter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jKamprapporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKamprapporterActionPerformed(evt);
            }
        });

        jTurneringsstilling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Division 1", "Division 2", "Division 3" }));
        jTurneringsstilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTurneringsstillingActionPerformed(evt);
            }
        });

        jSøgefelt.setText("Søg efter spiller eller klub");

        jSøgeknap.setText("Søg");
        jSøgeknap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSøgeknapActionPerformed(evt);
            }
        });

        jLabel48.setText("Kamprapporter");

        jLabel49.setText("Turneringsstilling");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTurneringsstilling, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jKamprapporter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jOpretKamp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel48))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSøgefelt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jSøgeknap)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKamprapporter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOpretKamp))
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTurneringsstilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSøgefelt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSøgeknap))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Oversigt", jPanel1);

        jLabel1.setText("Hjemmehold");

        jLabel2.setText("Udehold");

        jLabel3.setText("Sted");

        jLabel4.setText("Dato");

        jLabel5.setText("Tid");

        jOpretStartRapport.setText("Opret");
        jOpretStartRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpretStartRapportActionPerformed(evt);
            }
        });

        jAnnullerStartRapport.setText("Annuller");
        jAnnullerStartRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnullerStartRapportActionPerformed(evt);
            }
        });

        jLabel6.setText("Kamprapport");

        jLabel7.setText("Rundenummer");

        jLabel9.setText("Dommer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jStedOpret)
                                .addComponent(jDatoOpret)
                                .addComponent(jTidOpret)
                                .addComponent(jTeRundenrOpret, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDommerOpret, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(jUdeOpret))
                            .addComponent(jHjemmeOpret, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jOpretStartRapport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAnnullerStartRapport)))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jHjemmeOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jUdeOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jStedOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDatoOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTidOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTeRundenrOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jDommerOpret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOpretStartRapport)
                    .addComponent(jAnnullerStartRapport))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opret", jPanel2);

        jStedSe.setText("Sted");

        jDatoSe.setText("Dato");

        jTidSe.setText("Tid");

        jTextField12.setText("Udehold");

        jHjemmeholdSe.setText("Hjemmehold");

        jKampRedigerSe.setText("Rediger");
        jKampRedigerSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKampRedigerSeActionPerformed(evt);
            }
        });

        jKampTilbageSe.setText("Tilbage");
        jKampTilbageSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKampTilbageSeActionPerformed(evt);
            }
        });

        jLabel50.setText("vs");

        jStartopstillingSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Startopstilling" }));

        jLabel8.setText("Dommer");

        jDommerSe.setText("Dommer");

        jRundenrSe.setText("runde");

        jMålHjemmeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mål" }));

        jSelvmålHjemmeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selvmål" }));

        jAdvarselHjemmeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Advarsler" }));

        jUdvisningHjemmeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Udvisninger" }));

        jTextField2.setText("Antal tilskurer");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Startopstilling" }));

        jMålUdeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mål" }));

        jSelvmålUdeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selvmål" }));

        jAdvarselUdeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Advarsler" }));

        jUdvisningUdeSe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Udvisninger" }));

        jBegivenhedSe.setText("Begivenhed");
        jBegivenhedSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBegivenhedSeActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Afsluttet kamp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jStedSe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDatoSe, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTidSe, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRundenrSe, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jUdvisningHjemmeSe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAdvarselHjemmeSe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jMålHjemmeSe, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDommerSe))
                                .addComponent(jStartopstillingSe, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                                .addComponent(jHjemmeholdSe, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSelvmålHjemmeSe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jBegivenhedSe))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel50)
                                    .addComponent(jKampRedigerSe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jKampTilbageSe)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jAdvarselUdeSe, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSelvmålUdeSe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jMålUdeSe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(jUdvisningUdeSe, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTidSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatoSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStedSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRundenrSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHjemmeholdSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartopstillingSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jDommerSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jMålHjemmeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSelvmålHjemmeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdvarselHjemmeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUdvisningHjemmeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jMålUdeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSelvmålUdeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdvarselUdeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUdvisningUdeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKampRedigerSe)
                    .addComponent(jKampTilbageSe)
                    .addComponent(jBegivenhedSe))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Se", jPanel3);

        jGemBegivenhed.setText("Gem");
        jGemBegivenhed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGemBegivenhedActionPerformed(evt);
            }
        });

        jAnnullerBegivenhed.setText("Annuller");
        jAnnullerBegivenhed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnullerBegivenhedActionPerformed(evt);
            }
        });

        jBegivenhedHoldRediger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hjemmehold", "Udehold" }));

        jBegivenhedSpillerRediger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spiller" }));

        jBegivenhedTidRediger.setText("Tid");

        jBegivenhedRediger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mål", "Selvmål", "Advarsel", "Udvisning" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jBegivenhedRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBegivenhedHoldRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBegivenhedSpillerRediger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jBegivenhedTidRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jGemBegivenhed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jAnnullerBegivenhed)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBegivenhedHoldRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBegivenhedSpillerRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBegivenhedTidRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBegivenhedRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGemBegivenhed)
                    .addComponent(jAnnullerBegivenhed))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Begivenhed", jPanel4);

        jLabel19.setText("Turneringsstilling");

        jScrollPane1.setViewportView(jHoldListe);

        jStillingTilbage.setText("Tilbage");
        jStillingTilbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStillingTilbageActionPerformed(evt);
            }
        });

        jPlaceringsListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jPlaceringsListe);

        jScrollPane3.setViewportView(jResultatListe);

        jMålListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jMålListe);

        jPointListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jPointListe);

        jLabel14.setText("Nr");

        jLabel15.setText("Hold");

        jLabel16.setText("Point");

        jLabel17.setText("Mål");

        jLabel18.setText("Resultat");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jStillingTilbage))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16))
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStillingTilbage)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stilling", jPanel5);

        jLabel20.setText("Klub");

        jHoldKampeSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldKampeSeActionPerformed(evt);
            }
        });

        jLabel21.setText("Navn");

        jLabel22.setText("Adresse");

        jLabel23.setText("Spillere");

        jLabel24.setText("Træner");

        jLabel25.setText("Placering");

        jLabel26.setText("Kampe");

        jHoldRediger.setText("Rediger");
        jHoldRediger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldRedigerActionPerformed(evt);
            }
        });

        jHoldTilbage.setText("Tilbage");
        jHoldTilbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldTilbageActionPerformed(evt);
            }
        });

        jLabel51.setText("Sejre");

        jLabel52.setText("Uafgjort");

        jLabel53.setText("Tabte");

        jLabel54.setText("Point");

        jLabel55.setText("Mål");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jHoldRediger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jHoldTilbage)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jHoldTrænerSe)
                                    .addComponent(jHoldAdresseSe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoldNavnSe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoldSpillerSe, javax.swing.GroupLayout.Alignment.LEADING, 0, 133, Short.MAX_VALUE)
                                    .addComponent(jHoldPlaceringSe)
                                    .addComponent(jHoldKampeSe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHoldSejreSe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jHoldUafgjortSe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jHoldTabteSe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jHoldMålSe, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel53)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel55)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(jHoldPointSe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jHoldNavnSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jHoldAdresseSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jHoldSpillerSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jHoldTrænerSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jHoldPlaceringSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jHoldKampeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoldSejreSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldUafgjortSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldTabteSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldPointSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldMålSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoldTilbage)
                    .addComponent(jHoldRediger))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Klub", jPanel6);

        jLabel47.setText("Klub");

        jLabel56.setText("Placering");

        jHoldKampeRediger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldKampeRedigerActionPerformed(evt);
            }
        });

        jLabel57.setText("Kampe");

        jLabel58.setText("Sejre");

        jLabel59.setText("Uafgjort");

        jLabel60.setText("Tabte");

        jLabel61.setText("Mål");

        jLabel62.setText("Point");

        jHoldAnnuller.setText("Annuller");
        jHoldAnnuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldAnnullerActionPerformed(evt);
            }
        });

        jHoldGem.setText("Gem");
        jHoldGem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoldGemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHoldSejreRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel58))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jHoldUafgjortRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jHoldTabteRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jHoldMålRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel59)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel60)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel61)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(jHoldPointRediger, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel47)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel57))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jHoldPlaceringRediger)
                                    .addComponent(jHoldKampeRediger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jHoldGem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jHoldAnnuller)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jHoldPlaceringRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jHoldKampeRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addComponent(jLabel62)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoldSejreRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldUafgjortRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldTabteRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldPointRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHoldMålRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoldAnnuller)
                    .addComponent(jHoldGem))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rediger", jPanel7);

        jLabel33.setText("Navn");

        jLabel34.setText("Alder");

        jLabel35.setText("Kampe");

        jLabel36.setText("Mål");

        jLabel37.setText("Selvmål");

        jLabel38.setText("Advarsler");

        jSpillerRediger.setText("Rediger");
        jSpillerRediger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpillerRedigerActionPerformed(evt);
            }
        });

        jSpillerTilbage.setText("Tilbage");
        jSpillerTilbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpillerTilbageActionPerformed(evt);
            }
        });

        jLabel39.setText("Spiller");

        jLabel41.setText("Udvisninger");

        jLabel42.setText("Højeste antal mål i en kamp");

        jLabel43.setText("Bedømmelser");

        jLabel44.setText("Samlet bedømmelse");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(145, 325, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpillerBedømmelserSe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpillerSamletBedømmelseSe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpillerUdvisningSe)
                                    .addComponent(jSpillerHøjesteMålSe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpillerSelvmålSe)
                                    .addComponent(jSpillerAdvarselSe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpillerKampeSe)
                                    .addComponent(jSpillerMålSe, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpillerNavnSe)
                                    .addComponent(jSpillerAlderSe, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jSpillerRediger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpillerTilbage)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jSpillerNavnSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jSpillerAlderSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jSpillerKampeSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jSpillerMålSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jSpillerSelvmålSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jSpillerAdvarselSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jSpillerUdvisningSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jSpillerHøjesteMålSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jSpillerBedømmelserSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jSpillerSamletBedømmelseSe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpillerTilbage)
                    .addComponent(jSpillerRediger))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Spiller", jPanel8);

        jSpillerGem.setText("Gem");
        jSpillerGem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpillerGemActionPerformed(evt);
            }
        });

        jSpillerAnnuller.setText("Annuller");
        jSpillerAnnuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpillerAnnullerActionPerformed(evt);
            }
        });

        jLabel40.setText("Spiller");

        jLabel69.setText("Kampe");

        jLabel70.setText("Mål");

        jLabel71.setText("Selvmål");

        jLabel72.setText("Advarsler");

        jLabel73.setText("Udvisninger");

        jLabel74.setText("Højeste antal mål i en kamp");

        jLabel75.setText("Bedømmelser");

        jLabel76.setText("Samlet bedømmelse");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jSpillerGem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpillerAnnuller))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel70)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73)
                            .addComponent(jLabel74)
                            .addComponent(jLabel75)
                            .addComponent(jLabel76))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpillerBedømmelserRediger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpillerSamletBedømmelseRediger, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpillerUdvisningRediger)
                            .addComponent(jSpillerHøjesteMålRediger, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpillerSelvmålRediger)
                            .addComponent(jSpillerAdvarselRediger, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpillerKampeRediger)
                            .addComponent(jSpillerMålRediger, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(jSpillerKampeRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addComponent(jSpillerMålRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jSpillerSelvmålRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel72)
                    .addComponent(jSpillerAdvarselRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73)
                    .addComponent(jSpillerUdvisningRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jSpillerHøjesteMålRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(jSpillerBedømmelserRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jSpillerSamletBedømmelseRediger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpillerAnnuller)
                    .addComponent(jSpillerGem))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rediger", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTurneringsstillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTurneringsstillingActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jTurneringsstillingActionPerformed

    private void jHoldKampeSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldKampeSeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHoldKampeSeActionPerformed

    private void jHoldKampeRedigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldKampeRedigerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHoldKampeRedigerActionPerformed

    private void jOpretKampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpretKampActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jOpretKampActionPerformed

    private void jSøgeknapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSøgeknapActionPerformed
//        if (jSøgefelt.getText() == spiller) {
//            jTabbedPane1.setSelectedIndex(7);
//        }
//        if (jSøgefelt.getText() == klub) {
//            jTabbedPane1.setSelectedIndex(5);
//        } else {
//            System.out.println("Ugyldig søgning");
//        }
    }//GEN-LAST:event_jSøgeknapActionPerformed

    private void jKamprapporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKamprapporterActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jKamprapporterActionPerformed

    private void jOpretStartRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpretStartRapportActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jOpretStartRapportActionPerformed

    private void jAnnullerStartRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnullerStartRapportActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jAnnullerStartRapportActionPerformed

    private void jKampTilbageSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKampTilbageSeActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jKampTilbageSeActionPerformed

    private void jBegivenhedSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBegivenhedSeActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jBegivenhedSeActionPerformed

    private void jKampRedigerSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKampRedigerSeActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jKampRedigerSeActionPerformed

    private void jAnnullerBegivenhedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnullerBegivenhedActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jAnnullerBegivenhedActionPerformed

    private void jGemBegivenhedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGemBegivenhedActionPerformed
        if (jBegivenhedRediger.getSelectedItem() == "Mål") {
            if (jBegivenhedHoldRediger.getSelectedItem() == "Hjemmehold") {
                jMålHjemmeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            } else {
                jMålUdeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            }
        }
        
        if (jBegivenhedRediger.getSelectedItem() == "Selvmål") {
            if (jBegivenhedHoldRediger.getSelectedItem() == "Hjemmehold") {
                jSelvmålHjemmeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            } else {
                jSelvmålUdeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            }
        }
        
        if (jBegivenhedRediger.getSelectedItem() == "Advarsel") {
            if (jBegivenhedHoldRediger.getSelectedItem() == "Hjemmehold") {
                jAdvarselHjemmeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            } else {
                jAdvarselUdeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            }
        }
        
        if (jBegivenhedRediger.getSelectedItem() == "Udvisning") {
            if (jBegivenhedHoldRediger.getSelectedItem() == "Hjemmehold") {
                jUdvisningHjemmeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            } else {
                jUdvisningUdeSe.addItem(jBegivenhedSpillerRediger + jBegivenhedTidRediger.getText());
            }
        }
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jGemBegivenhedActionPerformed

    private void jStillingTilbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStillingTilbageActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jStillingTilbageActionPerformed

    private void jHoldRedigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldRedigerActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jHoldRedigerActionPerformed

    private void jHoldTilbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldTilbageActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jHoldTilbageActionPerformed

    private void jHoldGemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldGemActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jHoldGemActionPerformed

    private void jHoldAnnullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoldAnnullerActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jHoldAnnullerActionPerformed

    private void jSpillerRedigerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpillerRedigerActionPerformed
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_jSpillerRedigerActionPerformed

    private void jSpillerTilbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpillerTilbageActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jSpillerTilbageActionPerformed

    private void jSpillerGemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpillerGemActionPerformed
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jSpillerGemActionPerformed

    private void jSpillerAnnullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpillerAnnullerActionPerformed
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jSpillerAnnullerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurneringsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurneringsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurneringsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurneringsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurneringsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jAdvarselHjemmeSe;
    private javax.swing.JComboBox jAdvarselUdeSe;
    private javax.swing.JButton jAnnullerBegivenhed;
    private javax.swing.JButton jAnnullerStartRapport;
    private javax.swing.JComboBox jBegivenhedHoldRediger;
    private javax.swing.JComboBox jBegivenhedRediger;
    private javax.swing.JButton jBegivenhedSe;
    private javax.swing.JComboBox jBegivenhedSpillerRediger;
    private javax.swing.JTextField jBegivenhedTidRediger;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JTextField jDatoOpret;
    private javax.swing.JTextField jDatoSe;
    private javax.swing.JTextField jDommerOpret;
    private javax.swing.JTextField jDommerSe;
    private javax.swing.JButton jGemBegivenhed;
    private javax.swing.JTextField jHjemmeOpret;
    private javax.swing.JTextField jHjemmeholdSe;
    private javax.swing.JTextField jHoldAdresseSe;
    private javax.swing.JButton jHoldAnnuller;
    private javax.swing.JButton jHoldGem;
    private javax.swing.JTextField jHoldKampeRediger;
    private javax.swing.JTextField jHoldKampeSe;
    private javax.swing.JList jHoldListe;
    private javax.swing.JTextField jHoldMålRediger;
    private javax.swing.JTextField jHoldMålSe;
    private javax.swing.JTextField jHoldNavnSe;
    private javax.swing.JTextField jHoldPlaceringRediger;
    private javax.swing.JTextField jHoldPlaceringSe;
    private javax.swing.JTextField jHoldPointRediger;
    private javax.swing.JTextField jHoldPointSe;
    private javax.swing.JButton jHoldRediger;
    private javax.swing.JTextField jHoldSejreRediger;
    private javax.swing.JTextField jHoldSejreSe;
    private javax.swing.JComboBox jHoldSpillerSe;
    private javax.swing.JTextField jHoldTabteRediger;
    private javax.swing.JTextField jHoldTabteSe;
    private javax.swing.JButton jHoldTilbage;
    private javax.swing.JTextField jHoldTrænerSe;
    private javax.swing.JTextField jHoldUafgjortRediger;
    private javax.swing.JTextField jHoldUafgjortSe;
    private javax.swing.JButton jKampRedigerSe;
    private javax.swing.JButton jKampTilbageSe;
    private javax.swing.JComboBox jKamprapporter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jMålHjemmeSe;
    private javax.swing.JList jMålListe;
    private javax.swing.JComboBox jMålUdeSe;
    private javax.swing.JButton jOpretKamp;
    private javax.swing.JButton jOpretStartRapport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JList jPlaceringsListe;
    private javax.swing.JList jPointListe;
    private javax.swing.JList jResultatListe;
    private javax.swing.JTextField jRundenrSe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox jSelvmålHjemmeSe;
    private javax.swing.JComboBox jSelvmålUdeSe;
    private javax.swing.JTextField jSpillerAdvarselRediger;
    private javax.swing.JTextField jSpillerAdvarselSe;
    private javax.swing.JTextField jSpillerAdvarselSe1;
    private javax.swing.JTextField jSpillerAlderSe;
    private javax.swing.JButton jSpillerAnnuller;
    private javax.swing.JComboBox jSpillerBedømmelser1;
    private javax.swing.JComboBox jSpillerBedømmelserRediger;
    private javax.swing.JComboBox jSpillerBedømmelserSe;
    private javax.swing.JButton jSpillerGem;
    private javax.swing.JTextField jSpillerHøjesteMålRediger;
    private javax.swing.JTextField jSpillerHøjesteMålSe;
    private javax.swing.JTextField jSpillerHøjesteMålSe1;
    private javax.swing.JTextField jSpillerKampeRediger;
    private javax.swing.JTextField jSpillerKampeSe;
    private javax.swing.JTextField jSpillerKampeSe1;
    private javax.swing.JTextField jSpillerMålRediger;
    private javax.swing.JTextField jSpillerMålSe;
    private javax.swing.JTextField jSpillerMålSe1;
    private javax.swing.JTextField jSpillerNavnSe;
    private javax.swing.JButton jSpillerRediger;
    private javax.swing.JTextField jSpillerSamletBedømmelseRediger;
    private javax.swing.JTextField jSpillerSamletBedømmelseSe;
    private javax.swing.JTextField jSpillerSamletBedømmelseSe1;
    private javax.swing.JTextField jSpillerSelvmålRediger;
    private javax.swing.JTextField jSpillerSelvmålSe;
    private javax.swing.JTextField jSpillerSelvmålSe1;
    private javax.swing.JButton jSpillerTilbage;
    private javax.swing.JTextField jSpillerUdvisningRediger;
    private javax.swing.JTextField jSpillerUdvisningSe;
    private javax.swing.JTextField jSpillerUdvisningSe1;
    private javax.swing.JComboBox jStartopstillingSe;
    private javax.swing.JTextField jStedOpret;
    private javax.swing.JTextField jStedSe;
    private javax.swing.JButton jStillingTilbage;
    private javax.swing.JTextField jSøgefelt;
    private javax.swing.JButton jSøgeknap;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTeRundenrOpret;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTidOpret;
    private javax.swing.JTextField jTidSe;
    private javax.swing.JComboBox jTurneringsstilling;
    private javax.swing.JTextField jUdeOpret;
    private javax.swing.JComboBox jUdvisningHjemmeSe;
    private javax.swing.JComboBox jUdvisningUdeSe;
    // End of variables declaration//GEN-END:variables
}
